## Configuration file

name: Rabbit Care Double Languages
url: https://laemday.com

author: Là em đấy
description: This website specializes in storing rabbit breeding data in two languages ​​by Pham Xuan Tiep and tiepz.com studio. Including English and Vietnamese.
title: Rabbit Care Double Languages

permalink: /:year/:month/:day/:title.html
markdown: kramdown

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      lang: vn
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en
