## Configuration file

name: Nileane
url: https://laemday.com

author: Là em đấy
description: Student in Geography & Urban Planning. In favor of an open web, and sometimes web designer. I’m a trans woman with a bunch of cute curls on my head.
title: Nileane

permalink: /:year/:month/:day/:title.html
markdown: kramdown

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      lang: fr
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en
